name: 同步仓库（不含子模块）

on:
  push:
    branches: [ master ]
    tags: [ '*' ]  # 添加标签触发器来捕获标签推送

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 检出源仓库
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史
        token: ${{ secrets.SYNC_TOKEN }}

    - name: 配置Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: 移除子模块
      run: |
        # 移除子模块目录
        rm -rf assets/resource
        
        # 移除.gitmodules文件
        rm -f .gitmodules
        
        # 如果.git/config中有子模块配置，也移除它
        git config --local --unset-all submodule.assets/resource.url || true
        git config --local --unset-all submodule.assets/resource.active || true

    - name: 移除同步工作流
      run: |
        # 移除同步工作流文件，避免无限循环
        rm -f .github/workflows/sync-repo.yml
        
        # 提交变更
        git add -A
        git commit -m "从 TanyaShue/MaaYYs 同步 - ${GITHUB_SHA}"

    - name: 推送到目标仓库
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SYNC_TOKEN }}
        repository: TanyaShue/MFWPH
        branch: master
        force: true

    - name: 推送触发事件中的标签
      if: startsWith(github.ref, 'refs/tags/')  # 只在标签推送时执行
      run: |
        # 从github.ref获取推送的标签名
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "推送的标签: $TAG_NAME"
        
        # 创建一个临时目录
        mkdir -p ~/temp_repo && cd ~/temp_repo
        
        # 克隆目标仓库（浅克隆以提高速度）
        git clone --depth 1 https://${{ secrets.SYNC_TOKEN }}@github.com/TanyaShue/MFWPH.git .
        
        # 配置Git
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        
        # 创建标签指向目标仓库的HEAD
        git tag -f "$TAG_NAME" HEAD
        
        # 推送这个特定标签
        git push origin "$TAG_NAME" --force